### ISSUE TITLE
Doesn't work in Xcode 6.1

### ISSUE THREAD

**Issue by iosdev-republicofapps** [maranas/DebugSearch#4]
Hi,

This doesn't seem to work in Xcode 6.1.  Any ideas?  :-(  It looks awesome ...

Also, it talks about the file dbgHighlightConf.plist being created under ~ but I don't see it being created ...

Thanks!

**Comment by jakecraige** [comment]
:+1:

**Comment by e5faf2** [comment]
Yep, it seems like this plugin fails on Xcode 6.1 :(

**Comment by gerchicov-bp** [comment]
6.3.1 - the same

**Comment by maranas** [comment]
Hi guys,

I just upgraded to Xcode 6.1 and will have time to do this this week. Apologies for the late update, I was stuck with an older version of Xcode and didn't see the issue immediately.

**Comment by maranas** [comment]
I've added support for 6.3.2 - the latest Xcode should work now.

**Comment by iosdev-republicofapps** [comment]
Thanks!
