### ISSUE TITLE
xcode 6.3.2 - falls down

### ISSUE THREAD

**Issue by gerchicov-bp** [maranas/DebugSearch#5]
The plugin is installed and showed but falls down on a trying to filter console

**Comment by maranas** [comment]
Hi @gerchicov-bp , thank you for reporting the issue. I seem to have trouble reproducing it though; when I type a filter I only get log messages that contain that filter string as expected. Can you walk me through the steps to reproduce the bugs? Thanks in advance!

**Comment by gerchicov-bp** [comment]
Maybe it was a bug of xcode. I reinstalled it. First time after relaunch it closes xcode by itself again (so after install you need to run xcode twice). So it doesn't fall down but still doesn't work. I input something into the textfield, press enter and nothing happens. And this behaviour is always not single occurence.

**Comment by maranas** [comment]
@gerchicov-bp i see - nothing happens if you press enter; but it should filter the subsequent log messages. It doesn't clear messages that were already outputted, and it only filters the new ones. Is that the behavior you are observing?

**Comment by gerchicov-bp** [comment]
I didn't understand the phrase "Once a user starts debugging interactively, filters are ignored."
You should write in the Usage section "It doesn't clear messages that were already outputted, and it only filters the new ones."
Anyway sorry but it is useless for me with such limited functionality. I hope you are able to improve it. Look for example at MCLog:
https://github.com/yuhua-chen/MCLog

**Comment by maranas** [comment]
@gerchicov-bp thanks for the feedback, i feel that it is useful as it is and serves my purpose well so i thought i'd share. you are welcome to contribute if you think it can be better though, that's why it's on github.
