### ISSUE TITLE
Additional functionality for console?

### ISSUE THREAD

**Issue by gerchicov-bp** [maranas/DebugSearch#6]
If you filter the messages then maybe could you add a support of macro? I mean at least something easy, for example:
#define A   @"fdgd"
#define someMacro(x)   NSLog(@"%@", x)

The default xcode behaviour - all the macro code is not supported

**Comment by maranas** [comment]
Hi @gerchicov-bp,

Thanks for the suggestion, but IMO adding macro support is too use-case specific and is out of scope of the purpose of this project, which is just to filter and search debug output (something still lacking in the latest Xcode). This sounds like a good idea though, having macro support from the debugger.
