### ISSUE TITLE
Xcode 7.1 support

### ISSUE THREAD

**Issue by rciobanu-omnifone** [maranas/DebugSearch#8]
Tried with Alcatraz and tried cloning & building as well.
The Load/Skip bundles dialog doesn't come up when restarting Xcode, and the `defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1` doesn't show `DebugSearch` within the list of allowed plugins.

**Comment by imiller-gpfw** [comment]
Same for me.  Not showing up in XCode 7.1

**Comment by maranas** [comment]
Hi,
I just pushed a fix for this - d1288df1c4bab7be7345bbf4926afd6f5ab99e8c
